[package]
name = "reality_check"
version = "0.1.0"
description = "RealityCheck - Decentralized Media Verification"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "reality_check"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[dependencies]
anchor-lang = "0.32.1"
